Add the ability to subscribe to topic thanks to a regexp
senx/warp10-plugin-kafka pull request #3
Opened 2023-05-26 14:46 UTC by Giwi

Multiple syntaxes available : 
- Single topic subscription: `'topics'  'topic1'`
- Multiple topics subscription: `'topics' [ 'topic1' 'topic2' ]`
- Regexp subscription: `'topics'  '~topic(1-9).*'`

2023-06-02 14:45 UTC, hbs requested changes

2023-06-02 14:45 UTC, hbs commented on README.md
>  wf g -d CONFDIR -l LIBDIR io.warp10 warp10-plugin-kafka
Is that still the recommended way of installing the plugin?

2023-06-02 14:45 UTC, hbs commented on build.gradle
> +        mavenLocal()
should be removed no?

2023-06-02 14:45 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +      if (topic.startsWith("=") || topic.startsWith("~")) {
You don't need to use a prefix since a String parameter implies it is a regular expression.

2023-06-02 14:45 UTC, hbs commented on build.gradle
> +  implementation 'org.apache.kafka:kafka-clients:2.6.3'
Warp 10 3.x uses 3.4.0, the plugin for 3.x should not embed the kafka deps.

2023-06-02 14:45 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
>          @Override
indentation is off

2023-06-02 14:50 UTC, Giwi commented on build.gradle
> +        mavenLocal()
No, will be used by CI/CD for WarpFleet publication

2023-06-02 14:50 UTC, Giwi commented on README.md
>  wf g -d CONFDIR -l LIBDIR io.warp10 warp10-plugin-kafka
indeed

2023-06-02 14:53 UTC, Giwi commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +      if (topic.startsWith("=") || topic.startsWith("~")) {
No, L133 handles a single topic name as String

2023-06-08 08:01 UTC, hbs requested changes

2023-06-08 08:01 UTC, hbs commented on README.md
> +Where `W10DIR` is the root directory of your Warp 10 instance.
Use WARP10_HOME to be coherent with other names for the install directory

2023-06-08 08:01 UTC, hbs commented on README.md
> +  'topics'  '~topic(1-9).*'      // Regexp corresponding to Kafka topics to subscribe to
The '~' should be dropped

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +    // Hable topics
Hable?

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +      for (Object ktopic : kafkatopics) {
drop the ' ' before ':'

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +    for (Entry<Object, Object> entry : kafkaconfig.entrySet()) {
ditto, drop the ' ' before ':'

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +                consumer.subscribe(Pattern.compile(finalRegexp));
It would be better to check that the pattern is valid when it is first retrieved rather than delaying the compilation until the thread creation.

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +                for (ConsumerRecord<byte[], byte[]> record : records) {
drop the space

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +                  for (Header header : record.headers()) {
ditto

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +      for (Thread t : this.executors) {
ditto

2023-06-08 08:01 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaWarp10Plugin.java
> +        for (String spec : removed) {
ditto

2023-06-08 09:38 UTC, hbs commented on src/main/java/io/warp10/plugins/kafka/KafkaConsumer.java
> +      throw new RuntimeException("Invalid Kafka topic, MUST be a STRING or a List of thereof.");
or a List thereof

2023-06-08 09:52 UTC, hbs approved these changes

2023-06-08 09:52 UTC, merged